# Generated by Django 3.2.5 on 2021-11-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar_url',
            new_name='avatar',
        ),
    ]
